import fs            from 'node:fs/promises';
import path          from 'node:path';

const makeitjson = {
    en: {
        lang: 'ENG',
        ko: 'Korean',
        en: 'English',
        ja: 'Japanese',
        cht: 'Chat',
        mbr: 'Members',
        stg: 'Setting',
        home: 'Home',
        exit: 'Exit',
        cquit: 'Quit',
        exitep: 'If you exit, All data will be lost. Are you sure you want to exit?',
        exitas: 'What if you send a message to the developer to ask for help? or, save the chat log :)',
        cun: 'Change Username',
        ccn: 'Change Chat Name',
        mr: 'More',
        prfp: 'Add Profile Picture',
        op: 'Open',
        cls: 'Close',
        nch: 'Chat',
        ngch: 'Group Chat',
        src: 'Search here...',
        sdnmsg: 'Send a message',
        sdnpht: 'Send a photo',
        cld: 'Check calender',
        vprf: 'View Profile',
        addm: 'Invite more members',
        csts: 'Connection State',
        itrC: 'Send a message to start chatting.',
        empt: 'Empty',
        ukn: 'Unknown',
        chd: 'Checked',
        prep: 'This section is under development. Please wait.',
        uppr: 'Upload your image',
        sun: 'Sun',
        mon: 'Mon',
        tue: 'Tue',
        wed: 'Wed',
        thu: 'Thu',
        fri: 'Fri',
        sat: 'Sat',
        nevt: 'No event',
        tup: 'User profile',
        vinf: 'Portfolio information',
        gb: 'Go back',
        nf: 'Not found',
        cl: 'Change Languages',
        dkmd: 'Change Theme',
        dkmdl: 'Light Theme',
        dkmdd: 'Dark Theme',
        dkmds: 'System Theme',
        intro: 'Who I Am',
        education: 'Education',
        experience: 'Experience',
        skills: 'Skills and Expertise',
        projects: 'Projects',
        teamp: 'Team Projects',
        presentations: 'Presentations or Publications',
        personality: 'Interests and Hobbies',
        toc: 'Table of Contents',
        ist: 'Instagram',
        ghb: 'GitHub',
        aj: 'Ask developer',
        sem: 'Contact',
        sems: 'Email has been successfully sent.',
        semf: 'Too many emails or Invalid content. Try again later.',
        lks: 'Links',
        sq: 'Send a question',
        sd: 'Send',
        web: 'Write the email body here...',
        wrf: 'Where are you from? :)',
        kjy: 'Juyeon Kim',
        sj: 'Saitama, Japan',
        itr: 'Hi there! I\'m Juyeon Kim, a dedicated Node.js developer with a passion for programming and a deep understanding of economic principles. Currently pursuing my studies in Economy at Saitama University, I merge my technical expertise with domain knowledge to create innovative solutions at the intersection of technology and economics.',
        us: 'University Student',
        bch: 'Bachelor of Economics',
        rcw: 'Relevant Coursework',
        jpro: 'Janpara Omiya',
        rka: 'Republic of Korea Army',
        uqsm: 'Uniqlo Queen Street Mall',
        cien: 'Cross-Industry Experience',
        fsdm: 'Full Stack Development',
        lsls: 'Languages',
        susj: 'Saitama University, Saitama, Japan',
        egdm: 'Expected Graduation Date: March 2025',
        ecan: 'Economic Analysis',
        bsin: 'Business Innovation',
        nvag: 'November 2018 - August 2019',
        omsj: 'Omiya, Saitama, Japan',
        fese: 'Febrary 2020 - September 2021',
        pgrk: 'Paju-si, Gyeonggi-do, Republic of Korea',
        pgr1: 'Febrary 2022 - September 2022',
        pgr2: '170 Queen St, Brisbane City QLD 4000',
        pgr3: 'Bachelor of Economics',
        pgr4: 'Web Development Experience',
        pgr5: 'Node.js/JavaScript: 2 years',
        pgr6: 'HTML/CSS: 2 years',
        pgr7: 'AWS/Docker/Git: 1 year',
        pgr8: 'C++/Swift: 6 months',
        vmd: '"Vitmenu" is my very first project. It is a web application that provides a platform for users to create and share their own service. The application is built with Node.js, Express, and PostgreSQL. The front-end is built with HTML, CSS, and JavaScript, mainly running with React.js. The application is deployed on AWS EC2 and Docker containers. The application is currently under development. Feel free to check it out, or ask me about it in the chat!',
        vmdpf: 'This website "portfolio.vitmenu.com" is made for the chat feature which is intended to answer questions about me on behalf of the developer when the developer is not available, so that you can get to know me better in realtime, and I can get to know you better too. If you have any questions, please feel free to chat. Thank you.',
        zi: 'Zoom in',
        hb1: 'Computer Science Study',
        hb1desc: 'I enjoyed creating UMS maps, a sub-game of the game StarCraft, using an editor app from a young age. I found coding interesting and wanted to study it more deeply. Therefore, I am acquiring computer science knowledge based on internet information, regardless of my degree in economics. I am also interested in fields such as blockchain, artificial intelligence, big data, and data science, and I enjoy solving algorithm problems through sites like LeetCode and implementing original ideas into web applications.',
        hb2: 'Gym, Swimming, and European League Soccer',
        hb2desc: 'When I focus on studying, I spend a lot of time sitting in one position for a long time, so I reward myself by moving my body. Sometimes I go to the gym with friends or enjoy watching European league soccer games. I also enjoyed going to the swimming pool with friends from a young age, and I still maintain that habit.',
        hb3: 'Learning Languages',
        hb3desc: 'From attending university in Japan to participating in a working holiday, I enjoy experiencing various places and challenging myself with their cultures and lifestyles. Through these experiences, I aim to interact with diverse people, understand their thoughts and cultures, and gain a global perspective. Additionally, I enjoy learning different languages to communicate with various people.',
        hb4: '???',
        hb4desc: 'Ask me in the chat :)',
        li1: 'Talk to your team or the same company members',
        li2: 'Send images, videos, and files',
        li3: 'Make schedules and set reminders',
        sfi: 'Sorry for interupting...',
        mrag: 'It seems like you have reached the limitation of requests you can make as a guest user. Register your company to continue.',
        mrag1: 'It seems like you have reached the maximum number of requests you can make. Please wait a moment.',
        tcpe: 'Type your company name and press enter key',
        ni: 'Not interested',
        ierr1: 'Please enter the name of the company or organization.',
        ierr2: 'We couldn\'t find the matching page for you. Please try again.',
        lia: 'Log in as',
        tfu: 'Thank you for visiting my portfolio!',
        rgst: 'You will be able to',
        rgst1: 'Have you enjoyed',
        ftes1: '#1. Structure',
        pled2: '#2. Planned',
        sor: '#1. So far',
        frow: '#2. From now',
        lid0: "This portfolio features a simple chat app functionality and includes a unique aspect where, if I (the main character of the website) am not available, an assistant can act on my behalf. If you have any questions, the assistant will answer based on the resume I have prepared.",
        lid3: "It is planned to create a feature which analyses the content of user messages to understand their intentions and activate appropriate system actions. For instance, if a user's text message is related to scheduling, the AI will assist in creating the schedule, enabling more flexible interactions.",
        lid6: "Up until now, I have acquired foundational knowledge of TCP/IP and a web development tech stack centered around JavaScript to achieve the aforementioned objectives. Additionally, I have studied Docker and AWS services for hosting and deployment, as well as SQL and entity design methods through normalization for data management.",
        lid9: "My future goals, to be achieved by March 2025 before graduation, include learning the concepts of CI/CD to improve development and deployment speed, integrating payment APIs to activate the service as one with user permissions set by various plans, and ensuring stable operation as a paid service by performing server load testing using Apache Benchmark or JMeter.",
        wcpf: 'Welcome to Vitmenu chat!',
        fbam: 'Feel free to browse around and ask me anything you want to know about me.',
        qstn: '???',
        wsnw: 'Update',
        lodn: 'Loading',
        savd: 'Saved',
        erro: 'Error',
        rdmr: 'Read more',
        dvlg: 'Devlog',
        
        update: 'Company users can upload their profile photo now.',


        info: 'This portfolio website is made by Juyeon Kim. I am a full-stack developer who is passionate about creating web applications. I am currently looking for a job opportunity. If you are interested in me, please contact me. Thank you.',
        err: {
            50: 'Interval server error',
            40: 'Bad request',
            41: 'Unauthorized',
            44: 'Not found',
            429: 'Too many requests',
        },
        mesg: {
            tbf: 'File is too large, please upload a file smaller than 5MB.',
            dcl: 'Request declined. try again later.',
        },

        itrp0: '',
        educ0: '',
        expe0: '',
        skil0: '',
        achv0: '',
        prst0: '',
        psnl0: '',
        
        
    },
    ko: {
        lang: 'KOR',
        ko: '한국어',
        en: '영어',
        ja: '일본어',
        cht: '채팅',
        mbr: '멤버 목록',
        stg: '설정',
        home: '홈',
        exit: '나가기',
        cquit: '대화 삭제하기',
        exitep: '나가면 되돌아올 수 없습니다. 정말 나가시겠습니까?',
        exitas: '혹은 개발자에게 도움을 요청하거나, 채팅 로그를 저장해보세요.',
        cun: '닉네임 변경',
        ccn: '채팅방 이름 변경하기',
        mr: '더보기',
        prfp: '프로필 사진 추가하기',
        op: '열기',
        cls: '닫기',
        nch: '채팅',
        ngch: '그룹 채팅',
        src: '검색하기...',
        sdnmsg: '메시지를 입력하세요.',
        sdnpht: '사진 전송하기',
        cld: '캘린더 확인하기',
        vprf: '프로필 보기',
        addm: '멤버 초대하기',
        csts: '커넥션 상태',
        itrC: '채팅을 시작하려면 대화를 선택하거나 질문을 던져보세요.',
        empt: '비어있음',
        ukn: '알 수 없음',
        chd: '확인됨',
        prep: '여기는 현재 개발 중입니다.',
        uppr: '이미지를 업로드하세요',
        sun: '일',
        mon: '월',
        tue: '화',
        wed: '수',
        thu: '목',
        fri: '금',
        sat: '토',
        nevt: '이벤트 없음',
        tup: '유저 프로필',
        vinf: '포트폴리오 정보',
        gb: '뒤로가기',
        nf: '찾을 수 없습니다.',
        cl: '언어 변경하기',
        dkmd: '테마 변경하기',
        dkmdl: '라이트 테마',
        dkmdd: '다크 테마',
        dkmds: '시스템 테마',
        intro: '인트로',
        education: '학력',
        experience: '경력',
        skills: '기술 및 전문성',
        projects: '프로젝트',
        teamp: '팀 프로젝트',
        presentations: '발표 및 출판물',
        personality: '관심사 및 취미',
        toc: '목차',
        ist: '인스타그램',
        ghb: '깃허브',
        aj: '개발자에게 물어보기',
        sem: '연락하기',
        sems: '이메일이 성공적으로 전송되었습니다.',
        semf: '너무 많은 이메일이거나 옳바르지 않은 내용입니다. 잠시후 다시 시도하세요.',
        lks: '링크',
        sq: '질문 보내기',
        sd: '보내기',
        web: '여기에 이메일 본문을 작성하세요...',
        wrf: '당신은 어디서 오셨나요? :)',
        kjy: '김주연',
        sj: '사이타마, 일본',
        itr: '안녕하세요! 저는 김주연이라고 합니다. 프로그래밍에 열정을 가진 전문적인 Node.js 개발자입니다. 현재 사이타마 대학교에서 경제학을 공부하고 있으며, 기술적 전문성과 도메인 지식을 결합하여 기술과 경제의 교차점에서 혁신적인 솔루션을 만들어내고 있습니다.',
        us: '사이타마 대학',
        bch: '경제학 학사',
        rcw: '관련 과목',
        jpro: '잔파라 오오미야점',
        rka: '대한민국 육군',
        uqsm: '유니클로 퀸스트릿몰점',
        cien: '다양한 분야 경험',
        fsdm: '풀스택 개발',
        lsls: '언어',
        susj: '사이타마 대학교, 사이타마, 일본',
        egdm: '예정 졸업일: 2025년 3월',
        ecan: '경제 분석',
        bsin: '비즈니스 혁신',
        nvag: '2018년 11월 - 2019년 8월',
        omsj: '오미야, 사이타마, 일본',
        fese: '2020년 2월 - 2021년 9월',
        pgrk: '경기도 파주시, 대한민국',
        pgr1: '2022년 2월 - 2022년 9월',
        pgr2: '퀸스트리트 170번지, 브리즈번 시티 QLD 4000',
        pgr3: '경제학 학사',
        pgr4: '웹 개발 경험',
        pgr5: 'Node.js/JavaScript: 2년',
        pgr6: 'HTML/CSS: 2년',
        pgr7: 'AWS/Docker/Git: 1년',
        pgr8: 'C++/Swift: 6개월',
        vmd: '"Vitmenu"는 제가 웹 개발 독학을 시작했을 때, 웹 개발의 전반적인 지식을 습득하고자 시작한 로드맵과 같은 프로젝트입니다. 애플리케이션의 구상으로 양방향 통신의 프로토콜과 React의 Dynamic Rendering이라는 특징을 활용하여 사용자가 독창적인 웹 앱을 "vitmenu.com"의 서브 도메인으로 등록하고 소유하는 것으로 비지니스의 성장을 촉진할 수 있는 플랫폼을 계획했습니다.',
        vmdpf: '현재 보고 계시는 "portfolio.vitmenu.com"은 챗 기능을 중심으로한 제작된 웹 사이트입니다. 마스터키를 가진 유저가 부재중일 때 어시스턴트가 챗상에서 대신 대답해주는 것으로, 실시간으로 저와 여러분이 더 잘 알아갈 수 있도록 설계하였습니다. 질문이 있으시면 무엇이든 챗에서 물어보세요!',
        zi: '확대하기',
        hb1: '컴퓨터 과학 공부',
        hb1desc: '어려서부터 에디터 앱을 사용해서 스타크래프트라는 게임의 서브 게임인 유즈맵을 제작하는 것을 즐겨했습니다. 그러한 기억에서인지, 코딩을 하는 것에도 큰 흥미를 느꼇고 좀 더 깊게 공부하고 싶어졌습니다. 그러한 계기로 경제학부 학위와는 별개로 인터넷 정보를 기반으로 컴퓨터 공학 지식을 습득하고 있습니다. 그 밖에도 블록체인, 인공지능, 빅데이터, 데이터 과학등의 분야에도 관심이 있고 릿코드등의 사이트를 통해 알고리즘 문제를 푸는 것과 독창적인 아이디어를 웹 애플리케이션으로 구현하는 것도 즐겨합니다.',
        hb2: '헬스장과 수영, 유럽 리그 축구 시청',
        hb2desc: '공부등에 집중하다 보면 한 자세로 오래 앉아있는 시간이 많아져서 몸을 움직이는 것으로 자기 자신에게 보답해주고는 합니다. 때로는 친구와 헬스장에 가서 함께 운동하거나 유럽 리그 축구 경기를 보며 즐겁게 시간을 보내기도 합니다. 또한 어려서부터 친구들과 수영장에 다니는 걸 즐겨했었는데 아직도 그러한 습관을 유지하고 있습니다.',
        hb3: '언어 학습',
        hb3desc: '일본에 대학을 진학해 온 것부터 워킹홀리데이까지 다양한 곳을 경험하고 그곳의 문화와 생활에 도전하는 것을 좋아합니다. 그러한 경험을 통해 다양한 사람들과 소통하고 그들의 생각과 문화를 이해하며 세계적인 시각을 가지고 싶습니다. 또한 다양한 언어를 배워서 다양한 사람들과 소통하는 것을 좋아합니다.',
        hb4: '???',
        hb4desc: '채팅으로 물어보세요 :)',
        li1: '팀원이나 같은 회사 멤버들과 대화하기',
        li2: '이미지, 비디오, 파일 보내기',
        li3: '일정 만들기 및 알림 설정하기',
        sfi: '죄송합니다...',
        mrag: '조금 전의 리퀘스트가 게스트 유저의 요청 권한을 초과한 것 같습니다. 죄송하지만 회사를 등록하여 계속하세요.',
        mrag1: '요청할 수 있는 최대 횟수에 도달한 것 같습니다. 잠시만 기다려주세요.',
        tcpe: '회사 이름을 입력하고 엔터키를 누르세요',
        ni: '관심 없음',
        ierr1: '회사나 단체의 이름을 입력해주세요.',
        ierr2: '찾으시는 페이지를 찾을 수 없습니다. 조금 더 정확한 검색어로 다시 시도해주세요.',
        lia: '다음 회사로 로그인',
        tfu: '제 포트폴리오에 방문해주셔서 감사합니다!',
        rgst: '다음과 같은 기능을 사용하실 수 있습니다.',
        rgst1: '아래 항목들을 사용해 보셨나요?',
        ftes1: '#1. 구조',
        pled2: '#2. 계획',
        sor: '#1. 지금까지',
        frow: '#2. 지금부터',
        lid0: '챗 앱 기능의 제작에 앞서서 3개의 메인 엔티티와 2개의 브릿지 엔티티를 구상했습니다. 메인 엔티티에는 독립적인 Conv와 User엔티티와 Conv엔티티에 종속되는 Mesg엔티티가 존재합니다.  또, 각각의 엔티티간의 data joining을 위해서 2개의 브릿지 엔티티를 마련해두었습니다. 마지막으로 OpenAI의 Embeding 모델 결과를 저장하기 위해 마련된 독립적인 테이블들은 회사 검색 기능과 사용자 메시지 의도 분석을 위해 사용됩니다.',
        lid3: '사용자의 메시지 콘텐츠를 분석하여 사용자의 의도를 파악하고 그에 맞는 시스템 액션을 활성화할 수 있도록 만들 예정입니다. 가령, 사용자 텍스트 메시지가 스케쥴링과 관련이 있다면 AI를 통하여 스케쥴 작성을 대신해서 하는 것 처럼 더욱 유연한 상호작용을 가능하게 할 수 있도록 할 것입니다.',
        lid6: '지금까지는 상기의 목적을 달성하기 위해서 기초적인 tcp/ip 등에 관한 지식과 JavaScript를 중심으로한 웹 개발 기술 스택들을 습득해왔습니다. 또한, 호스팅과 배포등을 위해 Docker와 AWS의 서비스들, 데이터를 관리하기 위해 SQL과 Normalisation을 통한 엔티티 설계 방식들을 공부해왔습니다.',
        lid9: '지금부터의 목표로는 2025년 3월 졸업전까지, 개발 및 배포 속도의 향상을 위해서 CI/CD에 대한 개념을 익히는 것과 다양한 플랜에 의해 유저의 권한이 설정되는 서비스로서 활성화 할 수 있도록 결제 API의 도입 및 유료 서비스로서 안정적인 운영이 가능하도록 Apache Benchmark나 JMeter를 통한 서버 부하 테스트등을 실행하고 경험해보는 것이 목표입니다.',
        wcpf: 'Vitmenu 챗에 오신 것을 환영합니다!',
        fbam: '자유롭게 둘러보시고 궁금한 점이 있으면 물어보세요.',
        qstn: '???',
        wsnw: '업데이트',
        lodn: '로딩중',
        savd: '저장완료',
        erro: '에러',
        rdmr: '더 보기',
        dvlg: '데브로그',
        
        update: '회사 유저들은 이제 프로필 사진을 업로드할 수 있습니다.',



        info: '이 포트폴리오 웹사이트는 김주연에 의해 제작되었습니다. 저는 웹 애플리케이션을 만드는 것에 열정을 가진 풀스택 개발자입니다. 현재 취업 기회를 찾고 있습니다. 저에게 관심이 있으시면 연락주세요. 감사합니다.',
        err: {
            50: '서버 오류가 발생했습니다.',
            40: '잘못된 요청입니다.',
            41: '인증이 필요합니다.',
            44: '찾을 수 없습니다.',
            429: '요청이 너무 많습니다.',
        },
        mesg: {
            tbf: '파일이 너무 큽니다. 5MB보다 작은 파일을 업로드해주세요.',
            dcl: '요청이 거부되었습니다. 다시 시도해주세요.',
        },
        
        itrp0: '',
        educ0: '',
        expe0: '',
        skil0: '',
        achv0: '',
        prst0: '',
        psnl0: '',
        
    },
    ja: {
        lang: 'JPN',
        ko: '韓国語',
        en: '英語',
        ja: '日本語',
        cht: 'チャット',
        mbr: 'メンバー',
        stg: '設定',
        home: 'ホーム',
        exit: '退出',
        cquit: '会話削除',
        exitep: '退出すると元に戻すことはできません。本当に退出しますか？',
        exitas: 'もしくは、開発者に助けを求めるか、チャットログを保存してみてください :)',
        cun: 'ユーザー名変更',
        ccn: 'チャット名変更',
        mr: 'もっと見る',
        prfp: 'プロフィール写真追加',
        op: '開く',
        cls: '閉じる',
        nch: 'チャット',
        ngch: 'グループチャット',
        src: 'ここで検索...',
        sdnmsg: 'メッセージを入力してください。',
        sdnpht: '写真を送信する',
        cld: 'カレンダーを確認する',
        vprf: 'プロフィールを見る',
        addm: 'メンバーを招待する',
        csts: '接続状態',
        itrC: 'チャットを始めるには、会話を選択するか、質問を投げてみてください :)',
        empt: '空',
        ukn: '不明',
        chd: '確認済み',
        prep: 'このセクションは現在開発中です。',
        uppr: '画像をアップロードしてください',
        sun: '日',
        mon: '月',
        tue: '火',
        wed: '水',
        thu: '木',
        fri: '金',
        sat: '土',
        nevt: 'イベントなし',
        tup: 'ユーザープロフィール',
        vinf: 'ポートフォリオ情報',
        gb: '戻る',
        nf: '見つかりません。',
        cl: '言語を変更する',
        dkmd: 'テーマを変更する',
        dkmdl: 'ライトテーマ',
        dkmdd: 'ダークテーマ',
        dkmds: 'システムテーマ',
        intro: '自己紹介',
        education: '学歴',
        experience: '経験',
        skills: 'スキルと専門知識',
        projects: 'プロジェクト',
        teamp: 'チームプロジェクト',
        presentations: 'プレゼンテーションや出版物',
        personality: '興味と趣味',
        toc: '目次',
        ist: 'インスタグラム',
        ghb: 'ギットハブ',
        aj: '開発者に尋ねる',
        sem: 'Email',
        sems: 'メールが正常に送信されました。',
        semf: 'メールが多すぎるか、無効な内容です。後で再試行してください。',
        lks: 'リンク',
        sq: '質問を送る',
        sd: '送信する',
        web: 'ここにメール本文を書いてください...',
        wrf: 'あなたはどこから来ましたか？ :)',
        kjy: 'キムジュヨン',
        sj: '埼玉県, 日本',
        itr: 'こんにちは！私はキムジュヨンです。プログラミングに情熱を持つNode.js開発者です。現在埼玉大学で経済学を学んでおり、技術的専門知識とドメイン知識を融合して、技術と経済の交差点で革新的なソリューションを作り出しています。',
        us: '埼玉大学',
        bch: '経済学部',
        rcw: '関連科目',
        jpro: 'じゃんぱら大宮店',
        rka: '大韓民国陸軍',
        uqsm: 'ユニクロクイーンストリートモール店',
        cien: 'クロス業界経験',
        fsdm: 'フルスタック開発',
        lsls: '言語',
        susj: '埼玉大学, 埼玉県, 日本',
        egdm: '卒業予定日: 2025年3月',
        ecan: '経済分析',
        bsin: 'ビジネスイノベーション',
        nvag: '2018年11月 - 2019年8月',
        omsj: '大宮, 埼玉県, 日本',
        fese: '2020年2月 - 2021年9月',
        pgrk: '大韓民国京畿道坡州市',
        pgr1: '2022年2月 - 2022年9月',
        pgr2: 'クイーンストリート170番地, ブリスベン市 QLD 4000',
        pgr3: '経済学部',
        pgr4: 'Web開発経験',
        pgr5: 'Node.js/JavaScript: 2年',
        pgr6: 'HTML/CSS: 2年',
        pgr7: 'AWS/Docker/Git: 1年',
        pgr8: 'C++/Swift: 6ヶ月',
        vmd: '"Vitmenu"は私がウェブ開発の独学を始めた時、ウェブ開発の全般的な知識を習得したいと思って始めたロードマップのようなプロジェクトです。 アプリケーションの構想として、双方向通信(Bidirectional)のProtocolとReactのDynamic Renderingという特徴を活用し、ユーザーが独創的なウェブアプリを「vitmenu.com 」のサブドメインとして所有することでビジネスの成長を促進できるプラットフォームを計画しました。',
        vmdpf: '現在、ご覧の「portfolio.vitmenu.com 」はチャット機能を中心に制作されたウェブサイトです。マスターキーを持ったユーザーが不在の時にアシスタントがチャット上で代わりにコミュニケーションをしてくれることで、リアルタイムで私と皆さんがお互いもっとよく知っていけるように設計しました。質問があれば何でもチャットで聞いてください！',
        zi: '拡大する',
        hb1: 'コンピュータサイエンスの勉強',
        hb1desc: '幼い頃からスタークラフトというゲームのサブゲームであるUMSマップを作成することを楽しんでいました。コーディングが面白いと感じ、より深く学びたいと思いました。そのため、経済学の学位に関係なく、インターネット情報に基づいてコンピュータサイエンスの知識を習得しています。また、ブロックチェーン、人工知能、ビッグデータ、データサイエンスなどの分野にも興味があり、LeetCodeなどのサイトを通じてアルゴリズム問題を解決したり、オリジナルのアイデアをWebアプリケーションに実装したりすることを楽しんでいます。',
        hb2: 'ジム、水泳、ヨーロッパリーグサッカー',
        hb2desc: '勉強に集中すると、長時間同じ姿勢で座っている時間が多くなるため、体を動かすことで自分自身にご褒美を与えます。友達とジムに行ったり、ヨーロッパリーグのサッカーゲームを楽しんだりして時間を過ごすことがあります。幼い頃から友達と一緒に水泳場に行くことを楽しんでいましたが、今でもその習慣を維持しています。',
        hb3: '言語学習',
        hb3desc: '日本に大学進学したことからワーキングホリデーまで、様々な場所を経験し、その地の文化や生活に挑戦することが好きです。そうした経験を通じて、多様な人々と交流し、彼らの考え方や文化を理解し、国際的な視点を持ちたいと考えています。また、様々な言語を学び、いろいろな人々とコミュニケーションを取ることが好きです。',
        hb4: '???',
        hb4desc: 'チャットで質問してください :)',
        li1: 'チームや同じ会社のメンバーと話す',
        li2: '画像、ビデオ、ファイルを送信する',
        li3: 'スケジュールを作成し、リマインダーを設定する',
        sfi: '申し訳ありません...',
        mrag: '少し前のリクエストがゲストユーザーのリクエスト権限を超えたようです。申し訳ありませんが、会社を登録して続行してください。',
        mrag1: 'リクエストできる最大回数に達したようです。しばらくお待ちください。',
        tcpe: '会社名を入力してエンターキーを押してください',
        ni: '興味なし',
        ierr1: '会社や団体の名前を入力してください。',
        ierr2: 'お探しのページが見つかりませんでした。もう少し正確にご記入ください。',
        lia: '次の会社でログイン',
        tfu: '私のポートフォリオに訪問していただきありがとうございます！',
        rgst: '以下の機能を利用できます。',
        rgst1: '下の項目は楽しんでいただけましたか？',
        ftes1: '#1. 構造',
        pled2: '#2. 予定',
        sor: '#1. これまで',
        frow: '#2. これから',
        lid0: 'チャットアプリ機能の制作に先立ち、3 つのメインエンティティと2つのブリッジエンティティを構想しました。メインEntityとしては、独立的なConvとUserエンティティとConvエンティティに従属するMesgエンティティが存在します。また、それぞれのエンティティ間のdata joiningのために2つのブリッジエンティティを設けています。 最後に、OpenAIのEmbedingモデルの結果を保存するために設けられた独立したテーブルは、会社の検索機能とユーザーメッセージの意図分析のために使用されます。',
        lid3: 'ユーザーのメッセージコンテンツを分析し、ユーザーの意図を理解し、それに合ったシステムアクションをアクティブにする予定です。たとえば、ユーザーのテキストメッセージの意図を把握し、もしそれがスケジューリングなどのDBとSchedulerサービスに関連している場合、AIを介してスケジュール作成を代わりに行うなど、より柔軟な相互作用を可能にする予定です。',
        lid6: 'これまでは上記の目的を達成するために、基礎的なネットワークに関する知識やJavaScriptを中心としたウェブ開発技術スタックを習得してきました。また、HostingとDeploymentなどのためにDockerとAWSのサービス、データを管理するためにSQLとNormalisationを通じたエンティティ設計方式を勉強してきました。',
        lid9: 'これからの目標としては、2025年3月の大学卒業前までに、開発及び配布速度の向上のためにCI/CDについての概念をより鮮明に身につけることと、様々なプランによりユーザの権限が設定されるサービスとして活性化できるように、決済APIの導入及び有料サービスとしてステーブルなサーバー運営が可能になるよう、Apache BenchmarkやJMeterによるサーバ負荷テストなどを実行し、経験してみることを目標としております。',
        wcpf: 'Vitmenuチャットへようこそ！',
        fbam: 'お好きなだけお見て、私に知りたいことを何でも聞いてください。',
        qstn: '???',
        wsnw: '更新',
        lodn: 'ロード中',
        savd: '保存完了',
        erro: 'エラー',
        rdmr: '詳細を見る',
        dvlg: 'Devブログ',
        
        update: '会社ユーザーは今、プロフィール写真をアップロードできます。',



        info: 'このポートフォリオウェブサイトは、Juyeon Kimによって作成されました。私はWebアプリケーションを作成することに情熱を持つフルスタック開発者です。現在、仕事の機会を探しています。私に興味がある場合は、お問い合わせください。ありがとうございます。',
        err: {
            50: 'サーバーエラーが発生しました。',
            40: '不正なリクエストです。',
            41: '認証が必要です。',
            44: '見つかりません。',
            429: 'リクエストが多すぎます。',
        },
        mesg: {
            tbf: 'ファイルが大きすぎます。5MB未満のファイルをアップロードしてください。',
            dcl: 'リクエストが拒否されました。もう一度お試しください。',
        },

        itrp0: '',
        educ0: '',
        expe0: '',
        skil0: '',
        achv0: '',
        prst0: '',
        psnl0: '',
    
}}

const translator = async () => {
    const langs = path.resolve('src', 'http', 'static-private', 'langs');
    const files = await fs.readdir(langs);
    
    for (const file of files) {
        const fileExt = path.extname(file);
        const fileName = path.basename(file, fileExt);

        if (makeitjson[fileName]) {
            const stringified = JSON.stringify(makeitjson[fileName]);
            await fs.writeFile(path.resolve(langs, file), stringified);
        } else {
            console.log(`missing translation for ${fileName}`);
        };
    };
};

translator();